name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' && 
      (
        contains(github.event.comment.body, '@duyetbot rebase') ||
        contains(github.event.comment.body, '@duyetbot autosquash')
      )

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: ${{ contains(github.event.comment.body, 'autosquash') }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
